version: '3.8'

services:
  stats-server:
    build: ./stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: ycse
      SPRING_DATASOURCE_PASSWORD: qwerty12341

  stats-db:
    image: postgres:16.3
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=ycse
      - POSTGRES_PASSWORD=qwerty12341
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 10

  main-service:
    build: ./main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      main-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-db:5432/main
      SPRING_DATASOURCE_USERNAME: ycse
      SPRING_DATASOURCE_PASSWORD: qwerty12341

  main-db:
    image: postgres:16.3
    container_name: main-db
    ports:
      - "7542:5432"
    environment:
     - POSTGRES_DB=main
     - POSTGRES_USER=ycse
     - POSTGRES_PASSWORD=qwerty12341
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 10